### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Rafoula** [mankash/sophos#2]
Hello, I have this error:

:~/sophos$ scons deps
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd third_party/crypto && scons lib
scons: Reading SConscript files ...
Checking for C library boost_unit_test_framework... (cached) no
boost unit test framework not found
Skipping checks. Be careful!
scons: done reading SConscript files.
scons: Building targets ...
g++	 src/set_hash.cpp  => build/set_hash.o
In file included from src/ecmh/binary_field/detail/polynomial_base.hpp:5:0,
                 from src/ecmh/binary_field/GF2_127_63.hpp:3,
                 from src/ecmh/binary_field/GF2_254.hpp:3,
                 from src/ecmh/binary_elliptic_curve/GLS254.hpp:3,
                 from src/set_hash.cpp:25:
src/ecmh/utility/enable_if.hpp:16:39: fatal error: boost/utility/enable_if.hpp: No such file or directory
 #include <boost/utility/enable_if.hpp>
                                       ^
compilation terminated.
scons: *** [build/set_hash.o] Error 1
scons: building terminated because of errors.
scons: *** [third_party/crypto/library] Error 2
scons: building terminated because of errors.

Can someone help me? Thank you.

**Comment by mankash** [comment]
Hi @Rafoula -

The original repo is here https://gitlab.com/sse/sophos , I'm not the author. This is just a clone that I haven't yet executed/compiled.

Cheers
